version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/lib" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/gcf" # Location of package manifests
    schedule:
      interval: "daily"