steps:
- name: golang:1.16
  entrypoint: /bin/bash
  args:
  - -c
  - cd gcf && go mod download && go mod vendor
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - InitStaticFeedSettings
  - --source=gcf
  - --runtime=go116
  - --trigger-topic=trigger-InitStaticFeedSettings
  - --region=asia-northeast1
  - --project=${PROJECT_ID}
  - --env-vars-file=gcf/${PROJECT_ID}.yml
  - --set-secrets=SENTRY_DSN=projects/${PROJECT_ID}/secrets/SENTRY_DSN:latest
  - --service-account=feed-sa@${PROJECT_ID}.iam.gserviceaccount.com