steps:
- name: golang:1.16
  entrypoint: /bin/bash
  args:
  - -c
  - cd gcf && go version && ls -la && ls -la ../ && go mod download && echo hoge && go mod vendor
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - InvokeFeeds
  - --source=gcf
  - --runtime=go116
  - --trigger-topic=trigger-InvokeFeeds
  - --region=asia-northeast1
  - --project=${PROJECT_ID}
  - --env-vars-file=gcf/${PROJECT_ID}.yml
  - --set-secrets=DISCORD_BOT_TOKEN=projects/${PROJECT_ID}/secrets/DISCORD_BOT_TOKEN:latest,TWITTER_API_KEY=projects/${PROJECT_ID}/secrets/TWITTER_API_KEY:latest,TWITTER_API_SECRET=projects/${PROJECT_ID}/secrets/TWITTER_API_SECRET:latest,SENTRY_DSN=projects/${PROJECT_ID}/secrets/SENTRY_DSN:latest
  - --service-account=feed-sa@${PROJECT_ID}.iam.gserviceaccount.com