on:
  pull_request: # FIXME 後で消す
  push:
    branches:
      - main
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: imjasonh/setup-ko@v0.4
      - run: KO_DOCKER_REPO=gcr.io/village-go-godzilla/feed ko build ./cmd/feed